spring.application.name=bookstore-management

spring.thymeleaf.cache=false
spring.profiles.active=mysql
server.error.whitelabel.enabled=false

logging.level.com.example.bookstore=INFO

server.port=${PORT:8080}